### ISSUE TITLE
Operador not

### ISSUE THREAD

**Issue by lfarah71** [aziontech/azion-queries#6]
blz ?
Notei que quando se utiliza o operador "not", sempre retorna um erro 500 no Azion Playground
ex: StatusAndGeolocCountryNameNOT (not.gql)
![Screenshot_7](https://github.com/aziontech/azion-queries/assets/62488373/f11ed8c8-b5dc-48e6-8913-6bae9af5c3a5)

**Comment by LucasGeneroso** [comment]
Boa tarde, Luiz! 
Tudo certo com você? 

Realmente estamos com problemas nesse operador. Estamos investigando para corrigirmos isso, muito obrigado por nos apontar esse erro. 

Assim que tiver alguma atualização te retorno aqui na issue.

**Comment by LucasGeneroso** [comment]
Boa tarde, Luiz!
Tudo bem?

Estou retornando aqui para lhe avisar que aplicamos a correção no ambiente de produção, conforme segue:

![image](https://github.com/aziontech/azion-queries/assets/36650872/29e9695b-0bce-4397-9357-a8ed5151f474)

Estarei encerrando essa Issue, caso encontre mais algum erro sinta-se à vontade para abrir uma nova.

Novamente muito obrigado por ter nos reportado esse problema.
